tickers:
  poland:
    CDR.WA: "CD Projekt"
    PLW.WA: "PlayWay"
    TEN.WA: "11 bit studios"
    BLO.WA: "Bloober Team"
    CIG.WA: "CI Games"
    PKO.WA: "PKO Bank Polski"
    PEO.WA: "Bank Pekao"
    ING.WA: "ING Bank Śląski"
    MBK.WA: "mBank"
    ALR.WA: "Alior Bank"
    PKN.WA: "PKN Orlen"
    TPE.WA: "Tauron Polska Energia"
    ENA.WA: "Enea"
    PGE.WA: "Polska Grupa Energetyczna"
    KGH.WA: "KGHM Polska Miedź"
    LPP.WA: "LPP"
    JSW.WA: "Jastrzębska Spółka Węglowa"
    DNP.WA: "Dino Polska"
    CPS.WA: "Cyfrowy Polsat"
    PZU.WA: "PZU"
    KRK.WA: "Kruk"
    ACP.WA: "Asseco Poland"
  europe:
    BMW.DE: "Bayerische Motoren Werke AG"
    SIE.DE: "Siemens AG"
    SAN.PA: "Sanofi"
    TTE.PA: "TotalEnergies SE"
    BP.L: "BP p.l.c."
    HSBA.L: "HSBC Holdings plc"
    VOW3.DE: "Volkswagen AG"
    RNO.PA: "Renault SA"
    NG.L: "National Grid plc"
    DB1.DE: "Deutsche Börse"
    AIR.PA: "Airbus"
    BAS.DE: "BASF"
    SAP.DE: "SAP"
    BNP.PA: "BNP Paribas"
    AZN.L: "AstraZeneca"
    NOVN.SW: "Novartis"
    ROG.SW: "Roche"
    NESN.SW: "Nestlé"
    DTE.DE: "Deutsche Telekom"
  usa:
    AAPL: "Apple Inc."
    MSFT: "Microsoft Corporation"
    TSLA: "Tesla, Inc."
    GOOGL: "Alphabet Inc."
    AMZN: "Amazon.com, Inc."
    NKE: "Nike, Inc."
    JPM: "JPMorgan Chase & Co."
    XOM: "Exxon Mobil Corporation"
    PFE: "Pfizer Inc."
    NVDA: "NVIDIA"
    META: "Meta Platforms"
    V: "Visa"
    MA: "Mastercard"
    DIS: "Walt Disney"
    NFLX: "Netflix"
    INTC: "Intel"
    AMD: "Advanced Micro Devices"
    CSCO: "Cisco Systems"
    KO: "Coca-Cola"
    PG: "Procter & Gamble"
    WFC: "Wells Fargo"
  global:
    7203.T: "Toyota Motor Corporation"
    9984.T: "SoftBank Group Corp."
    005930.KS: "Samsung Electronics Co., Ltd."
    2330.TW: "Taiwan Semiconductor Manufacturing Company Limited"
    BABA: "Alibaba Group Holding Limited"
    JD: "JD.com, Inc."
    INFY.NS: "Infosys Limited"
    RELIANCE.NS: "Reliance Industries Limited"
    TM: "Toyota Motor Corporation (ADR)"
    SONY: "Sony Group Corporation"
    TCTZF: "Tencent Holdings Limited"
    HDB: "HDFC Bank Limited"
    BRK-B: "Berkshire Hathaway"
    WMT: "Walmart"
    005380.KS: "Hyundai Motor"
    1211.HK: "BYD Company"
    8035.T: "Tokyo Electron"
    3690.HK: "Meituan"
    0700.HK: "Tencent Holdings"
    NTTYY: "Nippon Telegraph and Telephone"
    TCS.NS: "Tata Consultancy Services"